package com.isabela.TCC.enums;

import lombok.Data;
import lombok.Getter;

@Getter
public enum Escolaridade {
    ENSINO_FUNDAMENTAL_INCOMPLETO,
    ENSINO_FUNDAMENTAL_COMPLETO,
    ENSINO_MEDIO_INCOMPLETO,
    ENSINO_MEDIO_COMPLETO,
    ENSINO_TECNICO,
    GRADUACAO_INCOMPLETA,
    GRADUACAO_CURSANDO,
    GRADUACAO_COMPLETA,
    POS_GRADUACAO,
    MESTRADO,
    DOUTORADO,
    POS_DOUTORADO;
}
